### ISSUE TITLE
lvscare设计

### ISSUE THREAD

**Issue by cuisongliu** [sealyun/lvscare#9]
1.  lvscare  create / delete / reload
start  创建ipvs规则并创建虚拟网卡（可配置） 并定时刷新规则
stop  删除所有配置的规则
reload 重新加载配置
2. /etc/lvscare/conf.d  新增 .yaml 配置读取对应的配置
3. 配置lvscare.service

**Comment by fanux** [comment]
start等于之前的care是吧，网卡绑定我忘记好像有些情况导致不通

**Comment by fanux** [comment]
网卡绑定可能得加条原地址转换规则

**Comment by cuisongliu** [comment]
create、delete 还是 start/stop 合适？ 合并之前的create/care 命令，没必要拆成俩

**Comment by cuisongliu** [comment]
绑定网卡我是想跟k8s一样就好了。这个后面做到这在看。看看这个设计还有别的想法不

**Comment by fanux** [comment]
start stop 不合适， create delete合适

**Comment by fanux** [comment]
k8s可不是单纯的只绑了网卡，还做了一些iptables规则上的事，有些细节没学全很容易出问题 哈哈

**Comment by fanux** [comment]
reload可以不要吗？ 检测配置文件更新和轮训检测，与kubelet检测static pod一个理 我觉得更好

**Comment by cuisongliu** [comment]
> reload可以不要吗？ 检测配置文件更新和轮训检测，与kubelet检测static pod一个理 我觉得更好

嗯嗯，可以去掉。主要就是一个create delete

**Comment by fanux** [comment]
你说create和care一起，是给create加了参数？  create需要创建完程序立马退出，而care需要一直运行

**Comment by cuisongliu** [comment]
> 你说create和care一起，是给create加了参数？ create需要创建完程序立马退出，而care需要一直运行

没错，就是这个意思。其实这俩功能一样，只是一个有探测，一个没探测而已。

**Comment by fanux** [comment]
可以 不过始终感觉create是一次性运行的。
care命令或者run命令是不更贴切一点
```
lvscare care --run-once
或
lvscare run --run-once
```

**Comment by fanux** [comment]
我觉得还是用care命令，以和老版本有比较好的兼容性。 care也能比较好的体现守护的意思

**Comment by zshi456** [comment]
> 1. lvscare  create / delete / reload
>    start  创建ipvs规则并创建虚拟网卡（可配置） 并定时刷新规则
>    stop  删除所有配置的规则
>    reload 重新加载配置
> 2. /etc/lvscare/conf.d  新增 .yaml 配置读取对应的配置
> 3. 配置lvscare.service

lvscare 有创建虚拟网卡么，可配置的参数是什么，我貌似在代码里面没有找到

**Comment by evanlixin** [comment]
lvscare没有实现 master节点的动态更新。比如：master节点IP变了 或者 新增master节点的场景
